// Casos da verificação de isolamento (usados por isolation.mjs --mutate).
// mustFail: true  -> import proibido plantado FORA do adaptador; a verificação TEM de acusar.
// mustFail: false -> texto que só PARECE import (comentário, string, outro módulo, dentro
//                    do adaptador); a verificação NÃO pode acusar.
const ALIAS = "@/server/execution/effects/providers/mercadopago/capabilities";

export const SELF_TEST_CASES = [
  { name: "ESM import com alias @/ (lib/)", mustFail: true, path: "lib/execution/__mp_mutation__.ts",
    source: `import { MERCADOPAGO_CAPABILITIES } from "${ALIAS}";\nexport const x = MERCADOPAGO_CAPABILITIES;\n` },
  { name: "ESM import relativo (server/execution/effects/)", mustFail: true, path: "server/execution/effects/__mp_mutation__.ts",
    source: `import { MERCADOPAGO_CAPABILITIES as C } from './providers/mercadopago/capabilities';\n` },
  { name: "import type (server/)", mustFail: true, path: "server/__mp_mutation__.ts",
    source: `import type { MERCADOPAGO_CAPABILITIES } from "${ALIAS}";\n` },
  { name: "import com extensão .js (app/)", mustFail: true, path: "app/__mp_mutation__.ts",
    source: `import * as caps from "${ALIAS}.js";\n` },
  { name: "import só de efeito colateral (components/)", mustFail: true, path: "components/__mp_mutation__.tsx",
    source: `import "${ALIAS}";\n` },
  { name: "import multi-linha", mustFail: true, path: "lib/__mp_mutation__.ts",
    source: `import {\n  MERCADOPAGO_CAPABILITIES,\n} from\n  "${ALIAS}";\n` },
  { name: "re-export export * from (lib/)", mustFail: true, path: "lib/__mp_mutation__.ts",
    source: `export * from "${ALIAS}";\n` },
  { name: "re-export export { } from (server/)", mustFail: true, path: "server/__mp_mutation__.ts",
    source: `export { MERCADOPAGO_CAPABILITIES } from "${ALIAS}";\n` },
  { name: "import() dinâmico (app/)", mustFail: true, path: "app/__mp_mutation__.ts",
    source: `export const load = () => import("${ALIAS}");\n` },
  { name: "import() dinâmico com template sem interpolação", mustFail: true, path: "app/__mp_mutation__.ts",
    source: "export const load = () => import(`" + ALIAS + "`);\n" },
  { name: "require() CommonJS (lib/)", mustFail: true, path: "lib/__mp_mutation__.cjs",
    source: `const caps = require("${ALIAS}");\nmodule.exports = caps;\n` },
  { name: "import x = require() (TypeScript)", mustFail: true, path: "server/__mp_mutation__.ts",
    source: `import caps = require("${ALIAS}");\n` },
  { name: "vizinho do adaptador (providers/, fora de mercadopago/)", mustFail: true, path: "server/execution/effects/providers/__mp_mutation__.ts",
    source: `import { MERCADOPAGO_CAPABILITIES } from "./mercadopago/capabilities";\n` },
  { name: "caminho com ../ que sai e volta ao adaptador", mustFail: true, path: "server/workflows/__mp_mutation__.ts",
    source: `import { MERCADOPAGO_CAPABILITIES } from "../execution/effects/providers/mercadopago/../mercadopago/capabilities";\n` },
  { name: "import depois de um comentário e de uma string", mustFail: true, path: "lib/__mp_mutation__.ts",
    source: `// nada aqui\nconst s = "texto";\nimport { MERCADOPAGO_CAPABILITIES } from "${ALIAS}";\n` },
  { name: "re-export de DENTRO do adaptador (atalho)", mustFail: true, path: "server/execution/effects/providers/mercadopago/__mp_mutation__.ts",
    source: `export * from "./capabilities";\n` },

  // ---- falsos positivos: TÊM de passar ----
  { name: "comentário de linha com o import", mustFail: false, path: "lib/__mp_control__.ts",
    source: `// import { MERCADOPAGO_CAPABILITIES } from "${ALIAS}";\nexport const a = 1;\n` },
  { name: "comentário de bloco com require e import()", mustFail: false, path: "server/__mp_control__.ts",
    source: `/*\n const c = require("${ALIAS}");\n import("${ALIAS}");\n*/\nexport const a = 1;\n` },
  { name: "string contendo o import inteiro", mustFail: false, path: "app/__mp_control__.ts",
    source: `export const doc = 'import { X } from "${ALIAS}"';\nexport const d2 = "require('${ALIAS}')";\n` },
  { name: "template contendo o import", mustFail: false, path: "components/__mp_control__.tsx",
    source: "export const t = `import x from \"" + ALIAS + "\"`;\n" },
  { name: "a palavra capabilities solta", mustFail: false, path: "lib/__mp_control__.ts",
    source: `export const capabilities = { capabilities: "capabilities.ts" };\n` },
  { name: "outro módulo chamado capabilities", mustFail: false, path: "lib/__mp_control__.ts",
    source: `import { x } from "@/lib/capabilities";\nimport y from "./capabilities";\n` },
  { name: "pacote externo com o mesmo nome", mustFail: false, path: "lib/__mp_control__.ts",
    source: `import z from "capabilities";\nimport w from "mercadopago/capabilities";\n` },
  { name: "regex literal contendo o caminho", mustFail: false, path: "lib/__mp_control__.ts",
    source: `export const re = /import .* from "@\\/server\\/execution\\/effects\\/providers\\/mercadopago\\/capabilities"/;\n` },
  { name: "import de DENTRO do adaptador (permitido)", mustFail: false, path: "server/execution/effects/providers/mercadopago/__mp_control__.ts",
    source: `import { MERCADOPAGO_CAPABILITIES } from "./capabilities";\nexport const n = MERCADOPAGO_CAPABILITIES.provider;\n` },
  { name: "propriedade obj.require(...) não é require", mustFail: false, path: "lib/__mp_control__.ts",
    source: `declare const obj: any;\nobj.require("${ALIAS}");\n` },
];
